spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: Rdis2fun
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
    test2:
      jdbc-url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: Rdis2fun
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver