spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: Rdis2fun
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring集成Mybatis环境
#加载Mybatis配置文件
mybatis:
  type-aliases-package: com.brotherc.springbootmybatis2.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml

